### ISSUE TITLE
error messages

### ISSUE THREAD

**Issue by july1206** [sworisbreathing/go-ibbq#10]
Hi.
Evry time I try to start I receive this error:
pls little bit of help?
Tnx!

sudo LOGXI=main=INF ./datalogger
14:09:45.913929 FTL main Error creating iBBQ
err: can't init hci: no devices available: (hci0: can't down device: device or resource busy)
goroutine 1 [running]:
runtime..z2fdebug.Stack
../../../src/libgo/go/runtime/debug/stack.go:24
github.com..z2fmgutz..z2flogxi..z2fv1.HappyDevFormatter.getLevelContext
/home/io/go/pkg/mod/github.com/mgutz/logxi@v0.0.0-20161027140823-aebf8a7d67ab/v1/happyDevFormatter.go:223
github.com..z2fmgutz..z2flogxi..z2fv1.HappyDevFormatter.Format
/home/io/go/pkg/mod/github.com/mgutz/logxi@v0.0.0-20161027140823-aebf8a7d67ab/v1/happyDevFormatter.go:307
github.com..z2fmgutz..z2flogxi..z2fv1.DefaultLogger.Log
/home/io/go/pkg/mod/github.com/mgutz/logxi@v0.0.0-20161027140823-aebf8a7d67ab/v1/defaultLogger.go:117
github.com..z2fmgutz..z2flogxi..z2fv1.DefaultLogger.extractLogError
/home/io/go/pkg/mod/github.com/mgutz/logxi@v0.0.0-20161027140823-aebf8a7d67ab/v1/defaultLogger.go:98
github.com..z2fmgutz..z2flogxi..z2fv1.DefaultLogger.Fatal
/home/io/go/pkg/mod/github.com/mgutz/logxi@v0.0.0-20161027140823-aebf8a7d67ab/v1/defaultLogger.go:107
main.main
/home/io/Downloads/go-ibbq-master/examples/datalogger/main.go:64

panic: Exit due to fatal error:

goroutine 1 [running]:
github.com..z2fmgutz..z2flogxi..z2fv1.DefaultLogger.Fatal
/home/io/go/pkg/mod/github.com/mgutz/logxi@v0.0.0-20161027140823-aebf8a7d67ab/v1/defaultLogger.go:109
main.main
/home/io/Downloads/go-ibbq-master/examples/datalogger/main.go:64

**Comment by sworisbreathing** [comment]
@july1206 the error you're getting is:
> err: can't init hci: no devices available: (hci0: can't down device: device or resource busy)

the go-ble library [requires exclusive access to the bluetooth device](https://github.com/go-ble/ble/issues/20#issuecomment-417627025).
