### ISSUE TITLE
Temperature graph plotting for each probe?

### ISSUE THREAD

**Issue by philgood** [sworisbreathing/go-ibbq#4]
Hello, I have just come across your ibbq library. Great project.
I have just compiled and built the WebSocket. Do you think it would be difficult to plot temperature readings on a graph over time, to see the trend data? The app drops the graph when you close the app...

**Comment by sworisbreathing** [comment]
Thanks.

Adding a plot shouldn't be too difficult if you know frontend web development. I, however, do not :-)

The websocket app is just a demo anyway, and my intent is to keep the frontend dependency-free, but feel free to create your own project with a better frontend.

If you do end up creating a better UI (which shouldn't be hard, considering how basic mine is), let me know and I'll link to it in the README, so other people can have something a bit snazzier.

**Comment by philgood** [comment]
Will do. Time to learn some web development. Thanks again.
