### ISSUE TITLE
More of a question and less of an Issue

### ISSUE THREAD

**Issue by danielthrasher** [sworisbreathing/go-ibbq#6]
Just curious if you have ever throught about capturing this data from the datalogger or just the linux service and sending it to mqtt broker and then to a cloud based IOT service and visualizing the data that way?

If you have,  would love to know how.

**Comment by sworisbreathing** [comment]
Hi @danielthrasher - sorry for the delayed response.

No, that thought's never crossed my mind before, but it seems perfectly doable. Neither AWS nor Azure appear to provide an IoT SDK for golang, but paho mqtt has a golang implementation (which is what GCP's golang sample code uses) that you could develop an app against using go-ibbq as a library. Or you could pipe the datalogger output to a python/node/whatever app that does use one of the other IoT SDKs.

**Comment by tdack** [comment]
I just stumbled across this repo and mqtt is one of the things I was looking for. I'm not familiar with Go, however, have managed to get paho.mqtt.golang imported into the datalogger example and connecting to a broker.

Not knowing Go this is where I've come unstuck ...

```
/* main.go imports and other pre-amble */

/* variable for mqtt client */
var mqClient mqtt.Client

func batteryLevelReceived(batteryLevel int) {
        logger.Info("Received battery data", "batteryPct", strconv.Itoa(batteryLevel))
        token := mqClient.Publish("home/ibqq/battery", 0, false, strconv.Itoa(batteryLevel))
        token.Wait()
}

func main () {
        /* stuff to set up mqtt client */

       mqClient := mqtt.NewClient(opts)

       /* confirm mqtt client has connected to broker */
       /* rest of datalogger example */
}
```
This compiles fine, runs and connects to the mqtt broker, detects the iBBQ device and then promptly crashes at the first `batteryLevelReceived()` call
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x277f24]
```
I suspect that the `mqClient` variable isn't accessible in `batteryLevelRecieved()`. Any suggestions on what I'm doing wrong appreciated.

See [`main.go`](https://gist.github.com/tdack/fe787535b10b7415deefdec052908fd0) for all the changes.

**Comment by tdack** [comment]
I worked out what I was doing wrong, `:=` and `=` are two different things in Go. `:=` initialises a new variable, so in the `main` function when creating a new mqtt client it was also creating a whole new local variable, however, the helper functions earlier were referencing/pointing at the `mqClient` variable declared globally. Valuable lesson on variable scopes.
